# .travis.yml
#sudo: false

#branches:
  #except:
    #- gh-pages
     

# variables that will be used in generateDocumentationAndDeploy.sh
env:
  global:
    - GH_REPO_NAME: 2020_20310814_Woranan
    - DOXYFILE: $TRAVIS_BUILD_DIR/worksheet7/Doxyfile
    - GH_REPO_REF: github.com/woranank/2020_20310814_Woranan.git

# The virtual machines created by Travis do not by default have doxygen
# installed. This is fortunately not difficult on a Debian flavoured Linux
# system.
addons:
  apt:
    packages:
      - doxygen
      - graphviz

# Finally we define the script that Travis will run every time code is submitted
# to the repository.
script:
  - cd worksheet7
  - cmake .
  - make
  - make test
  - cd ..
  
# After successfully building and testing your software we give Doxygen the
# instruction to scan the code for docstrings and generate the html output.
# The bulk of these instructions is encapsulated in a script.
after_success:
  #- cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
